name: Nix
on:
  push:
    branches: [ master ]
  pull_request: {}
  merge_group:
permissions:
  contents: read

jobs:
  build:
    name: Nix Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run flake checks with nix-fast-build
        run: nix run --inputs-from . nixpkgs#nix-fast-build -- --no-nom --skip-cached --flake .#checks
